name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source emsdk_env.sh
          cd ..
          curl -L https://github.com/raysan5/raylib/releases/download/3.7.0/raylib-3.7.0_webassembly.zip > rlib.zip
          unzip rlib.zip
          rm -rf rlib.zip
          echo
          echo "emcc src/main.c -o index.html -Iraylib-3.7.0_webassembly/include -Lraylib-3.7.0_webassembly/lib -lraylib"
          echo
          emcc src/main.c -o index.html -Iraylib-3.7.0_webassembly/include -Lraylib-3.7.0_webassembly/lib -lraylib

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
